name: KillSound
version: 1.2.0
main: net.wobble.killsound.KillSound
api-version: '1.21'
authors: [Wobble]
description: Configurable kill sound plugin.

softdepend:
  - WobbleSettings

commands:
  killsound:
    description: Manage KillSound
    usage: /killsound reload

permissions:
  killsound.reload:
    description: Reload KillSound configuration
    default: op
